version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./etc/nginx/ssl:/etc/nginx/ssl:ro"
      - "./logs:/var/log/nginx/"
      - "${LOCAL_DIR}:${DOCKER_DIR}"
    depends_on:
      - mysql
      - php-fpm
    command: [ "nginx","-g","daemon off;" ]
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-${MYSQL_VERSION}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  mysql5.6:
    image: mysql:5.6
    container_name: mysql-5.6
    restart: always
    ports:
      - "3305:3306"
    volumes:
      - "./data/db/mysql5.6:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${REDIS_VERSION}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/db/redis:/data"
      - "./etc/redis/redis.conf:/etc/redis.conf"
    command: [ "redis-server", "/etc/redis.conf" ]
  php-fpm:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: php-${PHP_VERSION}
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro"
      - "./etc/cron.d/crontab:/etc/cron.d/crontab:ro"
      - "${LOCAL_DIR}:${DOCKER_DIR}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    #  PMA_ARBITRARY: 1
    # 是否允许连接外部mysql

    #用nginx的转发80端口出来,这样可以80端口绑定虚拟主机
    #    ports:
    #      - "8000:80"
    depends_on:
      - mysql
      - nginx